In [1]:
import numpy as np

# Maximize:

### z = $5x_{1}$ + $4x_{2}$
        
s.t.
            
$6x_{1} + 4x_{2} + s_{1}$ = 24

$ x_{1} + 2x_{2} + s_{2}$ =  6

$-x_{1} +  x_{2} + s_{3}$ =  1

$         x_{2} + s_{4}$ =  2

$x_{1}, x_{2} \geq$ 0

In [22]:
A = np.array([
    [6,4,1,0,0,0],
    [1,2,0,1,0,0],
    [-1,1,0,0,1,0],
    [0,1,0,0,0,1]
])

In [24]:
b = np.array([[24],[6],[1],[2]])

In [31]:
c = np.array([[5],[4],[0],[0],[0],[0]])

In [32]:
c_trans = c.transpose()

In [36]:
B = A[:, [2,3,4,5]]

In [37]:
B

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [38]:
B_inv = np.linalg.inv(B)

In [39]:
X = np.dot(B, b)

In [40]:
X

array([[24],
       [ 6],
       [ 1],
       [ 2]])

In [46]:
z = np.dot(c_trans[:, [2,3,4,5]], X)

In [47]:
z

array([[0]])