In [1]:
import numpy as np

# Maximize:

### z = $5x_{1}$ + $4x_{2}$
        
s.t.
            
$6x_{1} + 4x_{2} + s_{1}$ = 24

$ x_{1} + 2x_{2} + s_{2}$ =  6

$-x_{1} +  x_{2} + s_{3}$ =  1

$         x_{2} + s_{4}$ =  2

$x_{1}, x_{2} \geq$ 0

In [2]:
A = np.array([
    [6,4,1,0,0,0],
    [1,2,0,1,0,0],
    [-1,1,0,0,1,0],
    [0,1,0,0,0,1]
])

In [3]:
b = np.array([[24],[6],[1],[2]])

In [4]:
c = np.array([[5],[4],[0],[0],[0],[0]])

In [5]:
c_trans = c.transpose()

In [6]:
B = A[:, [2,3,4,5]]

In [7]:
B

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [8]:
B_inv = np.linalg.inv(B)

In [9]:
X = np.dot(B, b)

In [10]:
X

array([[24],
       [ 6],
       [ 1],
       [ 2]])

In [11]:
z = np.dot(c_trans[:, [2,3,4,5]], X)

In [12]:
z

array([[0]])

In [13]:
c.shape

(6, 1)

In [14]:
c_trans.shape

(1, 6)

In [15]:
c_trans[0]

array([5, 4, 0, 0, 0, 0])

In [16]:
enter = []
for i in range(6):
    temp = np.dot(c_trans[:, [2,3,4,5]], B_inv)
    if (i==0 or i==1):
        enter.append(float(np.dot(temp, A[:, [i]]) - c_trans[0][i]))

In [17]:
enter

[-5.0, -4.0]

In [18]:
entering_variable = enter.index(min(enter))

In [19]:
entering_variable

0

In [20]:
np.dot(B_inv, b)

array([[24.],
       [ 6.],
       [ 1.],
       [ 2.]])

In [21]:
np.dot(B_inv, A[:, [0]])

array([[ 6.],
       [ 1.],
       [-1.],
       [ 0.]])

In [22]:
leave = [x[0]/y[0] for x,y in zip(np.dot(B_inv, b), np.dot(B_inv, A[:, [0]])) if x[0]/y[0]>0 and y[0]!=0]

C:\Users\NITIN\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in double_scalars
  """Entry point for launching an IPython kernel.


In [23]:
for i,j in zip(np.dot(B_inv, A[:, [0]]), np.dot(B_inv, A[:, [0]])):
    print(i[0], j[0])

6.0 6.0
1.0 1.0
-1.0 -1.0
0.0 0.0


In [24]:
leave

[4.0, 6.0]

In [25]:
leaving_variable = leave.index(min(leave))

In [26]:
leaving_variable

0